version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ajv
    versions:
    - 7.0.2
    - 7.0.3
    - 7.1.0
    - 7.1.1
    - 8.2.0
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: "@types/puppeteer"
    versions:
    - 5.4.3
  - dependency-name: webp-converter
    versions:
    - 2.3.3
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
  - dependency-name: cli-progress
    versions:
    - 3.9.0
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.7
  - dependency-name: xmldom
    versions:
    - 0.4.0
  - dependency-name: "@types/express"
    versions:
    - 4.17.11
    - 4.17.9
  - dependency-name: ini
    versions:
    - 1.3.7
